<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6010a1068656c6c6f776f726c642e70726f746f120c6170702e50726f" .
            "746f627566221c0a0c48656c6c6f52657175657374120c0a046e616d6518" .
            "0120012809221d0a0a48656c6c6f5265706c79120f0a076d657373616765" .
            "180120012809324d0a074772656574657212420a0853617948656c6c6f12" .
            "1a2e6170702e50726f746f6275662e48656c6c6f526571756573741a182e" .
            "6170702e50726f746f6275662e48656c6c6f5265706c79220042300a1b69" .
            "6f2e677270632e6578616d706c65732e68656c6c6f776f726c64420f4865" .
            "6c6c6f576f726c6450726f746f5001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

